### ISSUE TITLE
Cannot read property 'ctx' of undefined

### ISSUE THREAD

**Issue by PainterPuppets** [Wufe/react-particles-js#28] opened 2018-03-21 09:34 UTC
![image](https://user-images.githubusercontent.com/22258327/37702386-4ab5c82a-2d2d-11e8-9069-65438de5fac4.png)

I used react-particle-js on my page, On this page i jump to another page and back, it will throw this error.

this is my code screenshots
![image](https://user-images.githubusercontent.com/22258327/37702592-ff5ff778-2d2d-11e8-8ee0-37b30d0aca07.png)

**Comment by potaty** [comment] 2018-04-10 05:09
I met this problem too, could you tell me your solution? Thanks very much! @PainterPuppets

**Comment by Wufe** [comment] 2018-05-10 20:31
It is almost assured that the function `canvasClear` in ParticlesLibrary throws the error.  
It is not clear tho why is this happening and why it is not easily reproducible.  

If someone can reproduce it, here is a sandbox: [Sandbox](https://codesandbox.io/s/40808yxrzx).

**Comment by potaty** [comment] 2018-06-04 06:17
So sorry @Wufe, even in the same environment, I could not reproduce it, version: 2.1.0.

**Comment by Wufe** [comment] 2018-06-06 05:03
Thanks @potaty I'm closing this one.

**Closed by Wufe** 2018-06-06 05:03 UTC
Labels: bug, cannot reproduce
